---
- name: Deploy application
  hosts: all
  vars:
    install_path: '/home/{{ ansible_user_id }}/bangbangnapster'

  tasks:
  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/martingaston/bangbangnapster.git'
      dest: "{{ install_path }}"
  
- name: Start Servers
  tasks:
  - name: Copy systemd service file
    become: yes
    ansible.builtin.template:
      src: templates/napster_server.service.j2
      dest: /lib/systemd/system/napster_server.service
  
  - name: Restart napster service
    become: yes
    ansible.builtin.systemd:
      name: napster
      state: restarted
      daemon-reload: yes

- name: Start Clients
  tasks:
  - name: Copy systemd service file
    become: yes
    ansible.builtin.template:
      src: templates/napster_client.service.j2
      dest: /lib/systemd/system/napster_client.service
  
  - name: Restart napster service
    become: yes
    ansible.builtin.systemd:
      name: napster
      state: restarted
      daemon-reload: yes

